### ISSUE TITLE
Incompatible with fabric

### ISSUE THREAD

**Issue by hellishcodes** [LogicalGeekBoy/logical_zoom#62]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Logical Zoom' (logical_zoom) 0.0.25 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by LogicalGeekBoy** [comment]
You need to add the fabric-api mod also as per the instructions.

https://modrinth.com/mod/fabric-api
